codecov:
  require_ci_to_pass: no  # Only macOS runs coverage, others just test
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "60...100"  # For bash scripts, 60%+ is good coverage

  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        flags:
          - bash

    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  bash:
    paths:
      - lib/
      - hooks/
    carryforward: true

ignore:
  - "test/**"
  - "docs/**"
  - "*.md"
  - "sounds/**"
  - "config/**"
