name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            install_jq: sudo apt-get update && sudo apt-get install -y jq
          - os: macos-latest
            install_jq: brew install jq
          - os: windows-latest
            install_jq: choco install jq -y

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install jq (Linux/macOS)
        if: runner.os != 'Windows'
        run: ${{ matrix.install_jq }}

      - name: Install jq (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install jq -y
        shell: powershell

      - name: Verify jq installation
        run: jq --version
        shell: bash

      - name: Run test suite (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          chmod +x test/run-tests.sh
          ./test/run-tests.sh

      - name: Run test suite (Windows)
        if: runner.os == 'Windows'
        run: |
          bash test/run-tests.sh
        shell: bash

      - name: Test summary
        if: always()
        run: |
          if [ -f test-results.txt ]; then
            cat test-results.txt
          fi
        shell: bash
